### ISSUE TITLE
Dashboards without rows cause errors with "copy rows" command

### ISSUE THREAD

**Issue by KaylaHood** [grafana-wizzy/wizzy#131] opened 2018-09-12 21:51 UTC
https://github.com/utkarshcmu/wizzy/blob/915c5f9b0c2cf162b199f34e09fbf84bed38764b/src/local/components.js#L80

### Lesson: Dashboards Don't Always Have Rows
This line caused a very obscure error message when the dashboard I was modifying didn't have a `rows` attribute in the `srcDashboard` object seen in the function to which I linked this blame.

#### The Originating Command
The command I was using was `wizzy copy row 0 2`.

#### The Dashboard Being Operated On (JSON, important info marked with REDACTED)
```
{
  "__inputs": [
    {
      "description": "",
      "label": "REDACTED",
      "name": "REDACTED",
      "pluginId": "REDACTED",
      "pluginName": "REDACTED",
      "type": "datasource"
    }
  ],
  "__requires": [
    {
      "id": "grafana",
      "name": "Grafana",
      "type": "grafana",
      "version": "REDACTED"
    },
    {
      "id": "REDACTED",
      "name": "REDACTED",
      "type": "datasource",
      "version": "REDACTED"
    },
    {
      "id": "graph",
      "name": "Graph",
      "type": "panel",
      "version": "REDACTED"
    },
    {
      "id": "singlestat",
      "name": "Singlestat",
      "type": "panel",
      "version": "REDACTED"
    },
    {
      "id": "text",
      "name": "Text",
      "type": "panel",
      "version": "REDACTED"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "description": "REDACTED",
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "iteration": REDACTED,
  "links": [],
  "panels": [
    {
      "content": "REDACTED",
      "gridPos": {
        "h": 2,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 12,
      "links": [],
      "mode": "html",
      "title": "",
      "transparent": true,
      "type": "text"
    },
    {
      "cacheTimeout": null,
      "colorBackground": false,
      "colorValue": false,
      "colors": [
        "#299c46",
        "rgba(237, 129, 40, 0.89)",
        "#d44a3a"
      ],
      "datasource": "REDACTED",
      "decimals": null,
      "format": "none",
      "gauge": {
        "maxValue": 100,
        "minValue": 0,
        "show": false,
        "thresholdLabels": false,
        "thresholdMarkers": true
      },
      "gridPos": {
        "h": 2,
        "w": 24,
        "x": 0,
        "y": 2
      },
      "id": 10,
      "interval": null,
      "links": [],
      "mappingType": 1,
      "mappingTypes": [
        {
          "name": "value to text",
          "value": 1
        },
        {
          "name": "range to text",
          "value": 2
        }
      ],
      "maxDataPoints": 100,
      "nullPointMode": "connected",
      "nullText": null,
      "postfix": " REDACTED",
      "postfixFontSize": "50%",
      "prefix": "",
      "prefixFontSize": "50%",
      "rangeMaps": [
        {
          "from": "null",
          "text": "N/A",
          "to": "null"
        }
      ],
      "sparkline": {
        "fillColor": "rgba(31, 118, 189, 0.18)",
        "full": false,
        "lineColor": "rgb(31, 120, 193)",
        "show": false
      },
      "tableColumn": "count",
      "targets": [REDACTED],
      "thresholds": "",
      "title": "",
      "type": "REDACTED",
      "valueFontSize": "80%",
      "valueMaps": [
        {
          "op": "=",
          "text": "N/A",
          "value": "null"
        }
      ],
      "valueName": "max"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "REDACTED",
      "description": "",
      "fill": 1,
      "gridPos": {
        "h": 14,
        "w": 24,
        "x": 0,
        "y": 4
      },
      "hideTimeOverride": false,
      "id": 6,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "hideEmpty": true,
        "hideZero": true,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": false,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [
        {
          "type": "dashboard"
        }
      ],
      "nullPointMode": "null",
      "percentage": false,
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [REDACTED],
      "thresholds": [],
      "timeFrom": null,
      "timeShift": null,
      "title": "",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": "",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "content": REDACTED,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 18
      },
      "id": 8,
      "links": [],
      "mode": "html",
      "title": "",
      "transparent": true,
      "type": "text"
    }
  ],
  "refresh": false,
  "schemaVersion": 16,
  "style": "dark",
  "tags": [
    "REDACTED"
  ],
  "templating": {
    "list": [REDACTED]
  },
  "time": {
    REDACTED
  },
  "timepicker": {
    REDACTED
  },
  "timezone": "",
  "title": "REDACTED",
  "uid": "REDACTED"
}
```

**Comment by adj009** [comment] 2018-11-29 05:56
Same issue on my side.  Can't copy rows.

**Comment by Sytten** [comment] 2019-09-03 22:00
Duplicate of https://github.com/grafana-wizzy/wizzy/issues/131

**Closed by Sytten** 2019-09-03 22:00 UTC
Labels: bug
