### ISSUE TITLE
Allow importing a whole folder

### ISSUE THREAD

**Issue by nerdfacerory** [grafana-wizzy/wizzy#139] opened 2019-05-21 14:39 UTC
As we speak, the new folder support feature just displays in which folder you can find a certain dashboard, but you cannot import a whole folder. 
This might be a nice feature when you want to import a certain folder, not all the folders (what `wizzy import dashboards` would do) and there are too many dashboards in that folder to import each of them manually. 
Also, why do we need the creation of `dashboards` folder and then inside it are created the actual folders from Grafana? 
Why not create the Grafana folders directly without using this intermediary folder?

**Comment by Sytten** [comment] 2019-08-09 18:06
Duplicate of #123

**Closed by Sytten** 2019-08-09 18:06 UTC
Labels: feature request
